create table if not exists public.services (
  id bigint generated by default as identity primary key,
  icon text not null default 'wrench',
  title text not null check (length(trim(title)) > 0),
  description text not null default '',
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_settings
  add column if not exists show_services boolean not null default true,
  add column if not exists show_catalog boolean not null default true,
  add column if not exists show_contact boolean not null default true;

create index if not exists idx_services_sort_order on public.services(sort_order, id);

drop trigger if exists services_updated_at on public.services;
create trigger services_updated_at before update on public.services
for each row execute function public.update_settings_updated_at();

alter table public.services enable row level security;

create policy "Lectura pública servicios visibles" on public.services
  for select to anon using (is_visible = true);
create policy "Admin consulta servicios" on public.services
  for select to authenticated
  using (exists (select 1 from public.admin_users a where a.user_id = (select auth.uid())));
create policy "Admin inserta servicios" on public.services
  for insert to authenticated
  with check (exists (select 1 from public.admin_users a where a.user_id = (select auth.uid())));
create policy "Admin actualiza servicios" on public.services
  for update to authenticated
  using (exists (select 1 from public.admin_users a where a.user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users a where a.user_id = (select auth.uid())));
create policy "Admin elimina servicios" on public.services
  for delete to authenticated
  using (exists (select 1 from public.admin_users a where a.user_id = (select auth.uid())));

revoke insert, update, delete, truncate, references, trigger on public.services from anon;
grant select on public.services to anon;
grant select, insert, update, delete on public.services to authenticated;
grant usage, select on sequence public.services_id_seq to authenticated;

insert into public.services (icon, title, description, items, sort_order) values
  ('tractor', 'Maquinaria Agrícola', 'Venta y reparación de tractores, cosechadoras, empacadoras, segadoras y toda clase de maquinaria para el campo.', '["Tractores de todas las marcas","Empacadoras y rotoempacadoras","Segadoras y acondicionadoras","Remolques y aperos","Esparcidoras y abonadoras"]', 10),
  ('cow', 'Maquinaria Ganadera y Ordeño', 'Servicio técnico especializado en equipos para explotaciones ganaderas y salas de ordeño en el Valle de Pas.', '["Equipos de ordeño","Tanques de refrigeración de leche","Distribuidores de pienso","Cercas eléctricas","Bebederos y comederos automáticos"]', 20),
  ('tree', 'Maquinaria Forestal', 'Reparación y mantenimiento de todo tipo de maquinaria para trabajos forestales y de monte.', '["Motosierras profesionales","Desbrozadoras y rozadoras","Astilladoras de madera","Procesadoras forestales","Podadoras y telescópicas"]', 30),
  ('leaf', 'Maquinaria de Jardín', 'Distribuidores de la marca Rapid. Venta y reparación de segadoras hileradoras, cortacéspedes y tractores de jardín.', '["Segadoras hileradoras Rapid Euro","Segadoras Rapid 505 y 507","Tractores de jardín","Cortacéspedes profesionales","Motocultores y motoazadas"]', 40),
  ('star', 'Distribuidores Marca Rapid', 'Distribuidores oficiales de la marca Rapid para toda Cantabria. La mejor segadora hileradora del mercado.', '["Segadora hileradora Rapid Euro","Amplio stock piezas originales Rapid","Servicio técnico oficial","Modelos Rapid 505, 507 y más","Asesoramiento personalizado"]', 50),
  ('wrench', 'Taller de Reparación', 'Reparación integral de motores, sistemas hidráulicos, transmisiones, electricidad y soldadura en todo tipo de maquinaria.', '["Motores diesel y gasolina","Sistemas hidráulicos","Transmisiones y embragues","Diagnóstico electrónico","Soldadura MIG/TIG"]', 60),
  ('package', 'Venta de Recambios', 'Gran variedad de recambios originales para segadoras Rapid, Piva y todo tipo de maquinaria agrícola y de jardín.', '["Piezas originales Rapid","Recambios marca Piva","Filtros aceite, combustible y aire","Correas y cadenas","Cuchillas y accesorios"]', 70),
  ('calendar', 'Mantenimiento Preventivo', 'Planes de mantenimiento adaptados a cada máquina. Puesta a punto antes de campaña para evitar paradas.', '["Revisión general anual","Cambio de aceite y filtros","Afilado y ajuste de cuchillas","Revisión antes de temporada","Contratos de mantenimiento"]', 80);
