alter table public.site_settings
  add column if not exists home_badge text default 'Distribuidores Rapid · Toda Cantabria',
  add column if not exists brands_text text default '⭐ Rapid\n⭐ Piva\nJohn Deere\nFendt\nCase IH\nNew Holland\nMassey Ferguson\nDeutz-Fahr\nClaas\nSame\nHusqvarna\nStihl',
  add column if not exists why_us_text text default 'trophy|+20 años de experiencia|Décadas de trabajo con toda clase de maquinaria agrícola en Cantabria y alrededores.\nmicroscope|Diagnóstico avanzado|Herramientas de última generación para un diagnóstico preciso.\nzap|Servicio urgente|Atendemos urgencias con la mayor rapidez posible.\ncheck-circle|Garantía en reparaciones|Todos nuestros trabajos llevan garantía.',
  add column if not exists home_services_title text default 'Nuestros Servicios',
  add column if not exists home_services_description text default 'Servicio integral de reparación y mantenimiento para toda clase de maquinaria agrícola y tractores.',
  add column if not exists home_cta_title text default '¿Tu máquina tiene una avería?',
  add column if not exists home_cta_text text default 'Escríbenos por WhatsApp y te atendemos en el menor tiempo posible.',
  add column if not exists services_page_title text default 'Nuestros Servicios',
  add column if not exists services_page_description text default 'Venta y reparación de maquinaria agrícola, ganadera, forestal, de jardín y ordeño.',
  add column if not exists services_cta_title text default '¿Necesitas presupuesto?',
  add column if not exists services_cta_text text default 'Cuéntanos la avería y te damos un presupuesto sin compromiso.',
  add column if not exists catalog_page_title text default 'Catálogo de Piezas',
  add column if not exists catalog_page_description text default 'Consulta nuestro catálogo de piezas y recambios para maquinaria.',
  add column if not exists contact_page_title text default 'Contacta con Nosotros',
  add column if not exists contact_page_description text default 'Estamos en Selaya, Cantabria. Llámanos, mándanos un WhatsApp o visítanos.',
  add column if not exists legal_notice_text text default 'Talleres Enrique, con domicilio en C/ Pola n.º 2, Selaya, Cantabria.\n\nEste sitio informa sobre los servicios del taller, muestra un catálogo orientativo y facilita canales de contacto.',
  add column if not exists privacy_text text default 'La web no incluye formularios propios. Si contactas por teléfono, correo, Facebook o WhatsApp, los datos serán tratados para responder a tu consulta.\n\nPuedes ejercer tus derechos escribiendo al correo indicado en esta web.',
  add column if not exists cookies_text text default 'La web no instala cookies publicitarias ni de analítica. Solo guarda en el navegador las preferencias visuales elegidas.\n\nLos servicios externos pueden aplicar sus propias políticas.',
  add column if not exists legal_updated_at_text text default '25 de agosto de 2026',
  add column if not exists legal_pending boolean not null default true,
  add column if not exists wa_general_message text default 'Hola, quería consultar sobre una máquina o pieza.',
  add column if not exists wa_contact_message text default 'Hola, quería contactar con Talleres Enrique.',
  add column if not exists wa_pickup_message text default 'Hola, quería consultar sobre recogida o reparación en la explotación.',
  add column if not exists wa_part_message text default 'Hola, quería consultar por la pieza: {pieza} ({referencia}).',
  add column if not exists banner_enabled boolean not null default false,
  add column if not exists banner_title text default '',
  add column if not exists banner_text text default '',
  add column if not exists banner_type text default 'info',
  add column if not exists banner_link_label text default '',
  add column if not exists banner_link_url text default '',
  add column if not exists banner_start_at timestamptz,
  add column if not exists banner_end_at timestamptz;
